[build]
  publish = "./"
  command = ""

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Diese Zeile ist wichtig für die Formularverarbeitung
[[redirects]]
  from = "/success"
  to = "/results.html"
  status = 301
  force = true
